version: '3'

networks:
  dotman:
services:
  dotman:
    build: .
    container_name: dotman
    env_file:
      - env
    ports:
      - "1338:1338"
    volumes:
      - ./ssh_data:/ssh_data
    networks:
      - dotman
